# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mathaf Audio Guide
email: jcastillo@qm.org.qa
description: > # this means to ignore newlines until "baseurl:"
  A web-based audio guide theme for Jekyll.
baseurl: "/static-museum-audio-guide"
audio_path: "/audio/"
episode_hero_path: "/assets/img/stops/"
url: "https://jillian-nerice.github.io"
logo: "/assets/img/logo/audio-guide.png"
twitter_username: MathafModern
github_username:  jillian-nerice
menu_heading: "Select another stop"
index_page_text: "Select an audio guide stop to begin."
headphones_icon_dark: "/assets/img/icons/headphones-dark.png"
headphones_icon_light: "/assets/img/icons/headphones-light.png"
headphones_icon_green: "/assets/img/icons/headphones-green.png"
headphones_icon_red: "/assets/img/icons/headphones-red.png"


# Build settings
markdown: kramdown

# Version settings (version number below is used for cache busting CSS and JS)
version_number: 1.0.0.1
